export const SET_ALERT = 'SET ALERT';
export const REMOVE_ALERT = 'REMOVE ALERT';
export const REGISTER_SUCCESS = 'REGISTER SUCCESS';
export const REGISTER_FAIL = 'REGISTER FAIL';
export const USER_LOADED = 'USER LOADED';
export const AUTH_ERROR = 'AUTH ERROR';
export const LOGIN_SUCCESS = 'LOGIN SUCCESS';
export const LOGIN_FAIL = 'LOGIN FAIL';
export const LOGOUT = 'LOGOUT';
